// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package databse

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
}
